spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/app_booking_db
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: dev
  kafka:
    bootstrap-servers: localhost:9892
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/events_hotels?authSource=admin


app:
  database:
    init:
      enabled: false
  kafka:
    kafkaRoomBookedEventTopic: "room-booked-event-topic"
    kafkaUserRegistryEventTopic: "user-registry-event-topic"
    kafkaMessageGroupId: "kafka-app-group-id"